FROM python:3.11-alpine

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY ./src .

ENV PYTHONPATH=/app/models:/app/BaseModel

CMD ["python3.11", "main.py"]
